name: Automated API Quality Gate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  api-testing-matrix:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v4

    - name: Setup Node.js Runtime
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install && npm install express --save

    - name: Execute Enterprise Quality Gate Tests
      run: npx playwright test
      continue-on-error: true # Ensures compilation steps execute even when TC-004 throws its expected 500 fail code

    - name: Load Historical Metrics
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-dir

    - name: Build Allure Report Static Package
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages-dir
        allure_report: allure-report
        allure_history: allure-history

    - name: Archive HTML Assets to gh-pages Branch
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report

    - name: Pull Report Content from gh-pages Context
      uses: actions/checkout@v4
      if: always()
      with:
        ref: gh-pages
        path: deployment-payload

    - name: Setup GitHub Pages Layer
      uses: actions/configure-pages@v5
      if: always()

    - name: Upload Core Assets to Actions Deployment Engine
      uses: actions/upload-pages-artifact@v3
      if: always()
      with:
        path: 'deployment-payload'

    - name: Deploy Direct to Live Environments
      id: deployment
      uses: actions/deploy-pages@v4
      if: always()